### PR TITLE
SOP for glycerol stocks

### PR DESCRIPTION
**Pull request by steven-albanese**
Start of SOP for glycerol stocks

### CODE REVIEW

**Comment by steven-albanese** [comment]
Thanks @grundye!

**Comment by MehtapIsik** [comment]
Thanks for writing this protocol. I have few suggestions:

1) There is a typo in the directory name for glycerol stock.
2) "cryo-vial (screw top)" may not be clear to everyone. Can you add a link or picture of the tubes we use?
3) Preparation section: what temperature and fridge antibiotic aliquotes are stored? -20C
4) Day1: Can you add ethanol wiping of all surfaces as the first bullet point?
5) Add a note about where to put the glycerol stock: Shelf 11 of -80 C freezer. 
6) Can we add a "Record keeping" section after day 2?
     A draft:
## Record Keeping 
* Add an entry to glycerol stocks sheet of [Chodera Lab Plasmid Library](https://drive.google.com/open?id=1b-H7a3in7lu-r7KzwA7vuxOoumuTF1xGWB-hPrwuYCw). Record the vector, insert, and bacterial strain. 
* We currently store glycerol stocks in a box in Shelf 11 of -80 C freezer. If you create a new box or change location, update [Chodera Lab Fridge and Freezer Inventory](https://docs.google.com/spreadsheets/d/1F-x4JrbIAd96WqROiASZuANYdQVlM8HLVpmyp_6wbBY/edit?usp=sharing)

**Comment by steven-albanese** [comment]
Thanks @MehtapIsik! I think I've incorporated all of your suggestions and links

**Comment by MehtapIsik** [comment]
Looks great!

**Pull request merged**
