### PR TITLE
Caliper DNA chip protocol

### PR DESCRIPTION
**Pull request by dharaniazim**
Protocol for the Caliper DNA Assay.

### CODE REVIEW

**Comment by dharaniazim** [comment]
Could you review this protocol @MehtapIsik @steven-albanese

**Review by steven-albanese — CHANGES_REQUESTED** [review]
This looks good to me! 

One thing before we merge this: it looks like some screen shots got added to the top level of this repo. Could you rename them to be more informative and move them to the caliper protocol directory? You can create a subdirectory there called `images` or something to keep it neat!

**Comment by MehtapIsik** [comment]
Can you also remove `test.md` file?

**Comment by MehtapIsik** [comment]
Materials section - Can you add the recommended concentration range for DNA sample? Check if the DNA concentration range is the same for all the DNA kits.

**Review by steven-albanese — APPROVED** [review]

**Comment by MehtapIsik** [comment]
Please also add comments about the option to keep the chip with remaining reagents overnight in 4C fridge to use the next day. If less than a full plate of samples were run, usually enough reagent is left to do this. The chip needs to be primed and used the next day. After the run it must be properly cleaned and washed before long time storage.

**Comment by MehtapIsik** [comment]
Can you add the recommended concentration range for DNA sample to materials section? Why did you write 2 uL DNA sample is needed? Isn't ~40 uL sample needed when using 96 well PCR plate?

**Comment by MehtapIsik** [comment]
Thank you @ad316. This pull request is ready to be merged.

**Review by MehtapIsik — APPROVED** [review]

**Pull request merged**
